# Speculative Decoding Configuration for Hugging Face Models
# Uses tiny models for memory safety

# Model configuration
base_model: sshleifer/tiny-gpt2  # Base model for verification
draft_model: sshleifer/tiny-gpt2  # Draft model for proposal generation
max_draft: 2
implementation: hf  # Use Hugging Face models

# Draft mode configuration
draft_mode: vanilla  # vanilla, medusa, eagle
medusa:
  enabled: false
  num_heads: 2
  head_init: "tie"  # tie/copy/random
  temperature: 0.7
  top_p: 1.0
eagle:
  enabled: false
  alpha: 0.7
  max_draft: 2

# Generation parameters
temperature: 0.3
do_sample: false
max_new_tokens: 24  # Smaller for testing
top_p: 0.9
top_k: 50
repetition_penalty: 1.0

# Device and memory configuration
device: cpu  # Force CPU for stability
max_memory_mb: 500  # Memory limit for HF models

# Reproducibility
seed: 1234

# Logging configuration
log_level: INFO
verbose: false
