name: CI/CD Pipeline

# Trigger on push to main/dev branches and pull requests
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

# Environment variables
env:
  PYTHON_VERSION: "3.9"

jobs:
  # Lint and format check
  lint:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy psutil
          
      - name: Run Black (code formatting check)
        run: |
          # Only run if Python files exist
          if find src/ tests/ scripts/ -name "*.py" -type f | grep -q .; then
            black --check --diff --quiet src/ tests/ scripts/
          else
            echo "No Python files found to format"
          fi
        
      - name: Run isort (import sorting check)
        run: |
          # Only run if Python files exist
          if find src/ tests/ scripts/ -name "*.py" -type f | grep -q .; then
            isort --check-only --diff src/ tests/ scripts/
          else
            echo "No Python files found to sort"
          fi
        
      - name: Run Flake8 (linting)
        run: |
          # Only run if Python files exist
          if find src/ tests/ scripts/ -name "*.py" -type f | grep -q .; then
            flake8 src/ tests/ scripts/ --max-line-length=88 --extend-ignore=E203,W503,E402,E501,F401,F541,F811,F821,F841,W292,W293 --exit-zero
          else
            echo "No Python files found to lint"
          fi
        
      - name: Install type stubs
        run: |
          pip install types-requests types-PyYAML
          
      - name: Run MyPy (type checking)
        run: |
          # Only run if Python files exist
          if find src/ -name "*.py" -type f | grep -q .; then
            mypy src/ --ignore-missing-imports --no-strict-optional
          else
            echo "No Python files found to type check"
          fi

  # Unit tests (CPU only)
  test-cpu:
    name: Unit Tests (CPU)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest torch transformers psutil
          
      - name: Run CPU-only tests
        run: |
          # Run tests excluding GPU-specific tests
          pytest tests/ -k "not gpu" -v

  # Integration tests (simplified)
  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [lint, test-cpu]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest torch transformers psutil
          
      - name: Run integration tests
        run: |
          # Run integration tests that don't require actual GPU
          pytest tests/ -k "integration and not gpu" -v || echo "No integration tests found"
